parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your   database server
        connections:
            mysql:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
        default_entity_manager: mysql
        entity_managers:
            mysql:
                connection: mysql
                mappings:
                    MySQL:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/MySQL'
                        prefix: 'App\Entity\MySQL'
                        alias: MySQL
doctrine_mongodb:
    connections:
        mongodb:
            server: '%env(MONGODB_URL)%'
            options:
                db: '%env(MONGODB_DB)%'
#    default_database: '%env(MONGODB_DB)%'
    document_managers:
        mongodb:
#            auto_mapping: true
            mappings:
                MongoDB:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document/MongoDB'
                    prefix: 'App\Document\MongoDB'
                    alias: MongoDB